import type { ProductItem } from './product.types'

export const MOCK_PRODUCTS: ProductItem[] = [
	{
		id: 1,
		name: 'Vòng tay thạch anh trắng',
		description: 'Mang lại sự bình an và năng lượng tích cực.',
		category: {
			id: 1,
			name: 'Vòng tay phong thủy',
			description: 'Các loại vòng tay mang ý nghĩa phong thủy và may mắn.',
		},
		price: 350000,
		rating: 4.8,
		stock: 20,
		thumbnail:
			'https://tse1.explicit.bing.net/th/id/OIP.-7pqmcLqoemujrL8w8ROrAHaJ3?rs=1&pid=ImgDetMain&o=7&rm=3',
		images: [
			'https://kimtuthap.vn/wp-content/uploads/2019/12/vong-thach-anh-trang-duc-560x560.jpg',
			'https://trangsuc88.vn/wp-content/uploads/2019/11/12sad-3.jpg',
			'https://trangsucsen.com/wp-content/uploads/2023/11/vong-thach-anh-trang-01-min.jpg',
		],
	},
	{
		id: 2,
		name: 'Vòng tay mắt hổ nâu',
		description: 'Tăng sự tự tin và thu hút tài lộc.',
		category: {
			id: 1,
			name: 'Vòng tay phong thủy',
			description: 'Các loại vòng tay mang ý nghĩa phong thủy và may mắn.',
		},
		price: 420000,
		rating: 4.6,
		stock: 15,
		thumbnail: 'https://kaia.vn/wp-content/uploads/2018/12/untitled-46.jpg',
		images: [
			'https://product.hstatic.net/200000920459/product/vong_tay_mat_ho_nau_2a_8_mix_lu_thong_nephrite_ma_vang_d5891a16ba634335a0584f69b4789776.jpg',
			'https://ngocnhien.com/wp-content/uploads/vong-tay-da-mat-ho-nau-vang-8-ly-1.jpg',
		],
	},
	{
		id: 3,
		name: 'Vòng tay obsidian đen',
		description: 'Hỗ trợ xua đuổi năng lượng tiêu cực.',
		category: {
			id: 2,
			name: 'Vòng tay đá tự nhiên',
			description: 'Vòng tay làm từ đá tự nhiên cao cấp.',
		},
		price: 390000,
		rating: 4.7,
		stock: 18,
		thumbnail:
			'https://tse1.mm.bing.net/th/id/OIP.z78S1DlFGZJ5bsiuaPikDAHaJQ?rs=1&pid=ImgDetMain&o=7&rm=3',
		images: [
			'https://www.tuviphongthuy.vn/wp-content/uploads/2023/06/hac-dieu-thach.jpg',
			'https://tse1.explicit.bing.net/th/id/OIP.uzm4VkrmZN4y6nzU5foN_gHaGf?w=790&h=692&rs=1&pid=ImgDetMain&o=7&rm=3',
		],
	},
	{
		id: 4,
		name: 'Vòng tay thạch anh tím',
		description: 'Giúp cải thiện giấc ngủ và tăng sự tập trung.',
		category: {
			id: 2,
			name: 'Vòng tay đá tự nhiên',
			description: 'Vòng tay làm từ đá tự nhiên cao cấp.',
		},
		price: 450000,
		rating: 4.9,
		stock: 10,
		thumbnail: 'https://kaia.vn/wp-content/uploads/2018/11/v34.jpg',
		images: [
			'https://kimtuthap.vn/wp-content/uploads/2023/05/vong-tay-phong-thuy-thach-anh-tim.jpg',
			'https://bizweb.dktcdn.net/100/442/974/products/060323-11-copy.jpg?v=1685775951740',
			'https://ngocnhien.com/wp-content/uploads/2024/09/vong-tay-da-thach-anh-tim-dam_ngocnhien-1.jpg',
		],
	},
	{
		id: 5,
		name: 'Vòng tay mã não đỏ',
		description: 'Mang lại năng lượng tích cực và sự nhiệt huyết.',
		category: {
			id: 3,
			name: 'Vòng tay thời trang',
			description: 'Vòng tay thiết kế hiện đại, phù hợp nhiều phong cách.',
		},
		price: 320000,
		rating: 4.5,
		stock: 25,
		thumbnail: '/images/products/product-5.jpg',
		images: ['/images/products/product-5-1.jpg', '/images/products/product-5-2.jpg'],
	},
	{
		id: 6,
		name: 'Vòng tay aquamarine',
		description: 'Biểu tượng của sự bình tĩnh và giao tiếp hài hòa.',
		category: {
			id: 1,
			name: 'Vòng tay phong thủy',
			description: 'Các loại vòng tay mang ý nghĩa phong thủy và may mắn.',
		},
		price: 520000,
		rating: 4.8,
		stock: 8,
		thumbnail: '/images/products/product-6.jpg',
		images: ['/images/products/product-6-1.jpg', '/images/products/product-6-2.jpg'],
	},
	{
		id: 7,
		name: 'Vòng tay lapis lazuli',
		description: 'Tăng trí tuệ và khả năng sáng tạo.',
		category: {
			id: 2,
			name: 'Vòng tay đá tự nhiên',
			description: 'Vòng tay làm từ đá tự nhiên cao cấp.',
		},
		price: 480000,
		rating: 4.7,
		stock: 12,
		thumbnail: '/images/products/product-7.jpg',
		images: ['/images/products/product-7-1.jpg', '/images/products/product-7-2.jpg'],
	},
	{
		id: 8,
		name: 'Vòng tay aventurine xanh',
		description: 'Thu hút vận may và cơ hội trong công việc.',
		category: {
			id: 3,
			name: 'Vòng tay thời trang',
			description: 'Vòng tay thiết kế hiện đại, phù hợp nhiều phong cách.',
		},
		price: 300000,
		rating: 4.4,
		stock: 30,
		thumbnail: '/images/products/product-8.jpg',
		images: ['/images/products/product-8-1.jpg', '/images/products/product-8-2.jpg'],
	},
	{
		id: 9,
		name: 'Vòng tay moonstone',
		description: 'Cân bằng cảm xúc và nội tâm.',
		category: {
			id: 1,
			name: 'Vòng tay phong thủy',
			description: 'Các loại vòng tay mang ý nghĩa phong thủy và may mắn.',
		},
		price: 460000,
		rating: 4.6,
		stock: 14,
		thumbnail: '/images/products/product-9.jpg',
		images: ['/images/products/product-9-1.jpg', '/images/products/product-9-2.jpg'],
	},
	{
		id: 10,
		name: 'Vòng tay onyx đen',
		description: 'Biểu tượng của sức mạnh và sự bảo vệ.',
		category: {
			id: 2,
			name: 'Vòng tay đá tự nhiên',
			description: 'Vòng tay làm từ đá tự nhiên cao cấp.',
		},
		price: 380000,
		rating: 4.5,
		stock: 22,
		thumbnail: '/images/products/product-10.jpg',
		images: ['/images/products/product-10-1.jpg', '/images/products/product-10-2.jpg'],
	},
]
