import type { AccountItem } from './account.types'

export const MOCK_ACCOUNTS: AccountItem[] = [
	{
		id: 1,
		email: 'nguyenvana@gmail.com',
		phoneNumber: '0901234567',
		fullName: 'Nguyễn Văn A',
		gender: 'MALE',
		imageUrl: 'https://i.pravatar.cc/150?img=1',
		role: 'ADMIN',
	},
	{
		id: 2,
		email: 'tranthib@gmail.com',
		phoneNumber: '0912345678',
		fullName: 'Trần Thị B',
		gender: 'FEMALE',
		imageUrl: 'https://i.pravatar.cc/150?img=2',
		role: 'CLIENT',
	},
	{
		id: 3,
		email: 'leminhc@gmail.com',
		phoneNumber: '0923456789',
		fullName: 'Lê Minh C',
		gender: 'MALE',
		imageUrl: 'https://i.pravatar.cc/150?img=3',
		role: 'EMPLOYEE',
	},
	{
		id: 4,
		email: 'phamthid@gmail.com',
		phoneNumber: '0934567890',
		fullName: 'Phạm Thị D',
		gender: 'FEMALE',
		imageUrl: 'https://i.pravatar.cc/150?img=4',
		role: 'CLIENT',
	},
	{
		id: 5,
		email: 'hoangvane@gmail.com',
		phoneNumber: '0945678901',
		fullName: 'Hoàng Văn E',
		gender: 'MALE',
		imageUrl: 'https://i.pravatar.cc/150?img=5',
		role: 'EMPLOYEE',
	},
	{
		id: 6,
		email: 'doanthing@gmail.com',
		phoneNumber: '0956789012',
		fullName: 'Đoàn Thị F',
		gender: 'FEMALE',
		imageUrl: 'https://i.pravatar.cc/150?img=6',
		role: 'CLIENT',
	},
	{
		id: 7,
		email: 'vuquangh@gmail.com',
		phoneNumber: '0967890123',
		fullName: 'Vũ Quang H',
		gender: 'OTHER',
		imageUrl: 'https://i.pravatar.cc/150?img=7',
		role: 'EMPLOYEE',
	},
	{
		id: 8,
		email: 'buihoangi@gmail.com',
		phoneNumber: '0978901234',
		fullName: 'Bùi Hoàng I',
		gender: 'MALE',
		imageUrl: 'https://i.pravatar.cc/150?img=8',
		role: 'CLIENT',
	},
	{
		id: 9,
		email: 'dangthij@gmail.com',
		phoneNumber: '0989012345',
		fullName: 'Đặng Thị J',
		gender: 'FEMALE',
		imageUrl: 'https://i.pravatar.cc/150?img=9',
		role: 'EMPLOYEE',
	},
	{
		id: 10,
		email: 'nguyenkhangk@gmail.com',
		phoneNumber: '0990123456',
		fullName: 'Nguyễn Khang K',
		gender: 'OTHER',
		imageUrl: 'https://i.pravatar.cc/150?img=10',
		role: 'CLIENT',
	},
]
