export const PATH_ITEM = {
	HOME: {
		ROOT: '',
	},
	AUTH: {
		ROOT: 'auth',
		LOGIN: 'login',
		REGISTER: 'register',
	},
	PRODUCT: {
		ROOT: 'products',
		LIST_PRODUCT: 'list-product',
		DETAIL: ':id',
	},
	ADMIN: {
		ROOT: 'admin',
		DASHBOARD: 'dashboard',
		MANAGER_CATEGORY: 'manager-category',
		MANAGER_PRODUCT: 'manager-product',
		CREATE_PRODUCT: 'create-product',
		UPDATE_PRODUCT: 'update-product',
	},
}

export const ROUTE_PATH = {
	HOME: '/',
	AUTH: {
		LOGIN: `/${PATH_ITEM.AUTH.ROOT}/${PATH_ITEM.AUTH.LOGIN}`,
		REGISTER: `/${PATH_ITEM.AUTH.ROOT}/${PATH_ITEM.AUTH.REGISTER}`,
	},
	ADMIN: {
		DASHBOARD: `/${PATH_ITEM.ADMIN.ROOT}/${PATH_ITEM.ADMIN.DASHBOARD}`,
		MANAGER_CATEGORY: `/${PATH_ITEM.ADMIN.ROOT}/${PATH_ITEM.ADMIN.MANAGER_CATEGORY}`,
		MANAGER_PRODUCT: `/${PATH_ITEM.ADMIN.ROOT}/${PATH_ITEM.ADMIN.MANAGER_PRODUCT}`,
		CREATE_PRODUCT: `/${PATH_ITEM.ADMIN.ROOT}/${PATH_ITEM.ADMIN.CREATE_PRODUCT}`,
		UPDATE_PRODUCT: `/${PATH_ITEM.ADMIN.ROOT}/${PATH_ITEM.ADMIN.UPDATE_PRODUCT}:id`,
	},
	PRODUCT: {
		LIST_PRODUCT: `/${PATH_ITEM.PRODUCT.ROOT}/${PATH_ITEM.PRODUCT.LIST_PRODUCT}`,
		PRODUCT_DETAIL: `/${PATH_ITEM.PRODUCT.ROOT}/${PATH_ITEM.PRODUCT.DETAIL}`,
	},
}
